#!/bin/bash
cd /home/ubuntu/node-website
apt install https://rpm.nodesource.com/pub_16.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y
apt install nodejs -y --setopt=nodesource-nodejs.module_hotfixes=1
npm install forever@4.0.0 -g
