#!/bin/bash

cd /home/ubuntu

# Install python3
apt -y install python3-3.7.9-1.amzn2.0.2

# Install pip
apt -y install python3-pip-9.0.3
pip3 install -Iv --upgrade pip==20.2.1

# Install awscli and python dev libraries
pip3 install --user -r scripts/requirements.txt
