#!/bin/bash

cd /home/ubuntu

# Install python3
apt -y install python3

# Install pip
apt -y install python3


# Install awscli and python dev libraries
#pip3 install --user -r scripts/requirements.txt
